apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-delployment
  labels:
    app: myapp
    type: front-end
spec:
  replicas: 6
  template:
    metadata: 
      name: myapp-pod
      labels:
        app: myapp
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx 
  selector:
    matchLabels:
      app: myapp
      type: front-end