apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteOnce
    # - ReadOnlyMany
    # - ReadWriteMany
  capacity:
    storage: 1Gi
  # hostPath:
    # path: /tmp/dat not to use in a prd env.
  awsElasticBlockStore:
    volumeID: <volume-id>
    fsType: ext4
  