apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim
spec:
  accessModes:
    - ReadWriteOnce
  # storageClassName:  google-storage when u create a storage on cloud, this is the label u bind with sc-definition.yml
  resources:
    requests:
      storage: 500Mi