apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: google-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  # could be [ pd-standard | pd-ssd ]
  replication-type: none
  #could be [ none | regional-pd ]
# this files replace pv when u create a storage on GCP the pvc uses this files instead.